### ISSUE TITLE
Forward Model and Raw Data for Generating Synthetic Seismic

### ISSUE THREAD

**Issue by LukasMosser** [motazalfarraj/Elastic-Impedance-Inversion-Using-Recurrent-Neural-Networks#1]
Dear Motaz,

Thank you for sharing your implementation with your paper. 
Very interesting!

I was wondering, in your paper you state that the modeling for the synthetic seismic data (which you invert), you followed the approach outlined in Martin et al 2006.

Can you confirm this was done using a physics based approach using the same acquisition geometry and software used for the Marmousi 2 data?

Any chance to release the non-noisy data as well?

Many thanks!

**Comment by motazalfarraj** [comment]
Hi Lukas, 
Thanks for checking out the code. 

I followed the synthesis process outlined in Martin et al 2006 to generate the SYNTHETIC data as labeled in the released Marousi2 model. If you compare our seismic data with (0 angle) with the SYNTHETIC.segy seismic data released by Martin et al, they should be identical. However, we had to re-synthesize the seismic data for other incidents angle as well to estimate EI. However, we did not use the same software as Martin el al. 

As for the noise-free data, I'm not sure if I have it. However, since the elastic model of the marmousi2 is available it won't be hard to synthesize new data that is noise-free. You may also use the given forward model to synthesize simple noise-free data, unless you're looking for a more complex forward model. 

Thanks again, 
Motaz

**Comment by LukasMosser** [comment]
Many thanks for getting back to me on this and clearing up.
Can you share what software you used to create the other angle data?

Noise-free data I found on the marmousi-2 website, thanks!

**Comment by motazalfarraj** [comment]
Right. I did not use any software for that. I simply computed the AI, then computed the reflection coefficients( RC). Then I convolved the RC  with the wavelet specified in Martin et al. This process should get you the SYNTHETIC that can be found in Marmousi-2 website. 

For computation of RC for other angles, I computed elastic impedance using marmousi2 elastic model as detailed in AVO book then repeated the same process as AI. This should get you a simple synthetic Multioffset seismic data that we used to test our model. 


Let me know if you have any other questions. For non-code related questions, feel free to reach out by email (motaz[at]gatech.edu) 

Thanks
